# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import store_pb2 as store__pb2


class StoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.put = channel.unary_unary(
                '/app.Store/put',
                request_serializer=store__pb2.KeyValueModel.SerializeToString,
                response_deserializer=store__pb2.KeyValueModel.FromString,
                )
        self.get = channel.unary_unary(
                '/app.Store/get',
                request_serializer=store__pb2.Key.SerializeToString,
                response_deserializer=store__pb2.KeyValueModel.FromString,
                )
        self.getAllKeys = channel.unary_unary(
                '/app.Store/getAllKeys',
                request_serializer=store__pb2.Void.SerializeToString,
                response_deserializer=store__pb2.List.FromString,
                )


class StoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def put(self, request, context):
        """Add a key-value data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get(self, request, context):
        """Get a specific key-value data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getAllKeys(self, request, context):
        """Get all keys stored
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'put': grpc.unary_unary_rpc_method_handler(
                    servicer.put,
                    request_deserializer=store__pb2.KeyValueModel.FromString,
                    response_serializer=store__pb2.KeyValueModel.SerializeToString,
            ),
            'get': grpc.unary_unary_rpc_method_handler(
                    servicer.get,
                    request_deserializer=store__pb2.Key.FromString,
                    response_serializer=store__pb2.KeyValueModel.SerializeToString,
            ),
            'getAllKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.getAllKeys,
                    request_deserializer=store__pb2.Void.FromString,
                    response_serializer=store__pb2.List.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'app.Store', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Store(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/app.Store/put',
            store__pb2.KeyValueModel.SerializeToString,
            store__pb2.KeyValueModel.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/app.Store/get',
            store__pb2.Key.SerializeToString,
            store__pb2.KeyValueModel.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getAllKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/app.Store/getAllKeys',
            store__pb2.Void.SerializeToString,
            store__pb2.List.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
