# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='store.proto',
  package='app',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bstore.proto\x12\x03\x61pp\"+\n\rKeyValueModel\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x12\n\x03Key\x12\x0b\n\x03key\x18\x01 \x01(\t\"S\n\x04List\x12\x1f\n\x03map\x18\x01 \x03(\x0b\x32\x12.app.List.MapEntry\x1a*\n\x08MapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x06\n\x04Void2\x85\x01\n\x05Store\x12/\n\x03put\x12\x12.app.KeyValueModel\x1a\x12.app.KeyValueModel\"\x00\x12%\n\x03get\x12\x08.app.Key\x1a\x12.app.KeyValueModel\"\x00\x12$\n\ngetAllKeys\x12\t.app.Void\x1a\t.app.List\"\x00\x62\x06proto3'
)




_KEYVALUEMODEL = _descriptor.Descriptor(
  name='KeyValueModel',
  full_name='app.KeyValueModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='app.KeyValueModel.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='app.KeyValueModel.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=63,
)


_KEY = _descriptor.Descriptor(
  name='Key',
  full_name='app.Key',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='app.Key.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=83,
)


_LIST_MAPENTRY = _descriptor.Descriptor(
  name='MapEntry',
  full_name='app.List.MapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='app.List.MapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='app.List.MapEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=168,
)

_LIST = _descriptor.Descriptor(
  name='List',
  full_name='app.List',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='map', full_name='app.List.map', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_LIST_MAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=168,
)


_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='app.Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=176,
)

_LIST_MAPENTRY.containing_type = _LIST
_LIST.fields_by_name['map'].message_type = _LIST_MAPENTRY
DESCRIPTOR.message_types_by_name['KeyValueModel'] = _KEYVALUEMODEL
DESCRIPTOR.message_types_by_name['Key'] = _KEY
DESCRIPTOR.message_types_by_name['List'] = _LIST
DESCRIPTOR.message_types_by_name['Void'] = _VOID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KeyValueModel = _reflection.GeneratedProtocolMessageType('KeyValueModel', (_message.Message,), {
  'DESCRIPTOR' : _KEYVALUEMODEL,
  '__module__' : 'store_pb2'
  # @@protoc_insertion_point(class_scope:app.KeyValueModel)
  })
_sym_db.RegisterMessage(KeyValueModel)

Key = _reflection.GeneratedProtocolMessageType('Key', (_message.Message,), {
  'DESCRIPTOR' : _KEY,
  '__module__' : 'store_pb2'
  # @@protoc_insertion_point(class_scope:app.Key)
  })
_sym_db.RegisterMessage(Key)

List = _reflection.GeneratedProtocolMessageType('List', (_message.Message,), {

  'MapEntry' : _reflection.GeneratedProtocolMessageType('MapEntry', (_message.Message,), {
    'DESCRIPTOR' : _LIST_MAPENTRY,
    '__module__' : 'store_pb2'
    # @@protoc_insertion_point(class_scope:app.List.MapEntry)
    })
  ,
  'DESCRIPTOR' : _LIST,
  '__module__' : 'store_pb2'
  # @@protoc_insertion_point(class_scope:app.List)
  })
_sym_db.RegisterMessage(List)
_sym_db.RegisterMessage(List.MapEntry)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), {
  'DESCRIPTOR' : _VOID,
  '__module__' : 'store_pb2'
  # @@protoc_insertion_point(class_scope:app.Void)
  })
_sym_db.RegisterMessage(Void)


_LIST_MAPENTRY._options = None

_STORE = _descriptor.ServiceDescriptor(
  name='Store',
  full_name='app.Store',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=179,
  serialized_end=312,
  methods=[
  _descriptor.MethodDescriptor(
    name='put',
    full_name='app.Store.put',
    index=0,
    containing_service=None,
    input_type=_KEYVALUEMODEL,
    output_type=_KEYVALUEMODEL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get',
    full_name='app.Store.get',
    index=1,
    containing_service=None,
    input_type=_KEY,
    output_type=_KEYVALUEMODEL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getAllKeys',
    full_name='app.Store.getAllKeys',
    index=2,
    containing_service=None,
    input_type=_VOID,
    output_type=_LIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STORE)

DESCRIPTOR.services_by_name['Store'] = _STORE

# @@protoc_insertion_point(module_scope)
